-- ============================================================
-- SIZLIO POS - COMPLETE FRESH DATABASE SCHEMA
-- PostgreSQL 15+
-- Canonical bootstrap schema for a brand-new installation.
--
-- This file intentionally contains the tables used by the current
-- application, not only the original Phase-1 core tables.
-- Existing installations should use migrations instead.
-- ============================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- RESTAURANTS
-- ============================================================
CREATE TABLE public.restaurants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  owner_name VARCHAR(100),
  phone VARCHAR(30),
  email VARCHAR(150),
  city VARCHAR(100),
  address TEXT,
  plan VARCHAR(50) NOT NULL DEFAULT 'Basic',
  status VARCHAR(20) NOT NULL DEFAULT 'Active',
  expiry_date DATE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  logo_url VARCHAR(500),
  food_type VARCHAR(100) NOT NULL DEFAULT 'Fast Food',
  business_type VARCHAR(30) NOT NULL DEFAULT 'restaurant',

  -- POS / payment settings
  pos_settings JSONB NOT NULL DEFAULT '{}'::jsonb,
  raast_qr_string TEXT,

  -- Restaurant location / GPS lock
  latitude NUMERIC(10,7),
  longitude NUMERIC(10,7),
  gps_radius_meters NUMERIC(10,2) NOT NULL DEFAULT 100,

  -- Restaurant-level charge defaults
  delivery_charge NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (delivery_charge >= 0),
  dine_charge NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (dine_charge >= 0),
  card_charge NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (card_charge >= 0),
  bank_charge NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (bank_charge >= 0),

  -- FBR integration
  fbr_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  fbr_pos_registration_no VARCHAR(100),
  fbr_api_token TEXT,
  fbr_seller_ntn_cnic VARCHAR(100),
  fbr_seller_business_name VARCHAR(200),
  fbr_seller_province VARCHAR(100),
  fbr_seller_address TEXT,
  fbr_environment VARCHAR(20) NOT NULL DEFAULT 'sandbox'
    CHECK (fbr_environment IN ('sandbox','production'))
);

CREATE INDEX restaurants_status_idx ON public.restaurants(status);
CREATE INDEX restaurants_plan_idx ON public.restaurants(plan);

-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE public.users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL
    CHECK (role IN (
      'manager','waiter','kitchen','counter',
      'delivery','display','super_admin'
    )),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  restaurant_id INTEGER REFERENCES public.restaurants(id) ON DELETE CASCADE,

  current_session TEXT,
  last_login_at TIMESTAMPTZ,
  last_login_ip TEXT,
  last_login_device TEXT
);

CREATE INDEX users_restaurant_idx ON public.users(restaurant_id);
CREATE INDEX users_role_idx ON public.users(restaurant_id, role);
CREATE INDEX users_active_idx ON public.users(restaurant_id, is_active);

-- ============================================================
-- MENU CATEGORIES
-- ============================================================
CREATE TABLE public.menu_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (restaurant_id, name)
);

CREATE INDEX menu_categories_restaurant_idx
  ON public.menu_categories(restaurant_id, active);

-- ============================================================
-- MENU ITEMS
-- ============================================================
CREATE TABLE public.menu_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  category VARCHAR(100) DEFAULT 'Other',
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  image TEXT,
  package_size NUMERIC(12,3),
  package_unit VARCHAR(30)
);

CREATE INDEX menu_items_restaurant_idx
  ON public.menu_items(restaurant_id, active);
CREATE INDEX menu_items_category_idx
  ON public.menu_items(restaurant_id, category);

-- ============================================================
-- MENU ITEM VARIANTS
-- ============================================================
CREATE TABLE public.menu_item_variants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_item_id INTEGER NOT NULL
    REFERENCES public.menu_items(id) ON DELETE CASCADE,
  label VARCHAR(100) NOT NULL,
  price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (menu_item_id, label)
);

CREATE INDEX menu_item_variants_item_idx
  ON public.menu_item_variants(menu_item_id, active);

-- ============================================================
-- DEALS
-- ============================================================
CREATE TABLE public.deals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
  type VARCHAR(50) NOT NULL DEFAULT 'deal',
  category VARCHAR(100),
  image TEXT,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX deals_restaurant_idx ON public.deals(restaurant_id, active);

CREATE TABLE public.deal_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id INTEGER NOT NULL
    REFERENCES public.deals(id) ON DELETE CASCADE,
  menu_item_id INTEGER NOT NULL
    REFERENCES public.menu_items(id) ON DELETE RESTRICT,
  variant_id INTEGER
    REFERENCES public.menu_item_variants(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  UNIQUE (deal_id, menu_item_id, variant_id)
);

CREATE INDEX deal_items_deal_idx ON public.deal_items(deal_id);

-- ============================================================
-- INVENTORY / WAREHOUSE
-- ============================================================
CREATE TABLE public.suppliers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  phone VARCHAR(50),
  email VARCHAR(150),
  address TEXT,
  opening_balance NUMERIC(12,2) NOT NULL DEFAULT 0
    CHECK (opening_balance >= 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX suppliers_restaurant_idx
  ON public.suppliers(restaurant_id, is_active);

CREATE TABLE public.inventory_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  category VARCHAR(50) DEFAULT 'Other',
  unit VARCHAR(20) NOT NULL,
  package_size NUMERIC(12,3),
  package_unit VARCHAR(30),
  stock_quantity NUMERIC(12,2) NOT NULL DEFAULT 0
    CHECK (stock_quantity >= 0),
  minimum_stock NUMERIC(12,2) NOT NULL DEFAULT 0
    CHECK (minimum_stock >= 0),
  purchase_price NUMERIC(12,2) NOT NULL DEFAULT 0
    CHECK (purchase_price >= 0),
  supplier VARCHAR(100),
  supplier_id INTEGER
    REFERENCES public.suppliers(id) ON DELETE SET NULL,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX inventory_items_restaurant_idx
  ON public.inventory_items(restaurant_id, is_active);
CREATE INDEX inventory_items_supplier_idx
  ON public.inventory_items(supplier_id);

CREATE TABLE public.inventory_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id INTEGER NOT NULL
    REFERENCES public.inventory_items(id) ON DELETE RESTRICT,
  type VARCHAR(20) NOT NULL,
  quantity NUMERIC(12,2) NOT NULL CHECK (quantity > 0),
  note TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX inventory_transactions_item_idx
  ON public.inventory_transactions(inventory_id, created_at DESC);

-- ============================================================
-- MENU RECIPES
-- variant_id NULL = base menu-item recipe
-- ============================================================
CREATE TABLE public.menu_item_ingredients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_item_id INTEGER NOT NULL
    REFERENCES public.menu_items(id) ON DELETE CASCADE,
  inventory_id INTEGER NOT NULL
    REFERENCES public.inventory_items(id) ON DELETE CASCADE,
  variant_id INTEGER
    REFERENCES public.menu_item_variants(id) ON DELETE CASCADE,
  quantity NUMERIC(12,3) NOT NULL CHECK (quantity > 0),
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (menu_item_id, inventory_id, variant_id)
);

CREATE INDEX menu_item_ingredients_item_idx
  ON public.menu_item_ingredients(menu_item_id);
CREATE INDEX menu_item_ingredients_variant_idx
  ON public.menu_item_ingredients(variant_id);

-- ============================================================
-- KITCHEN INVENTORY
-- ============================================================
CREATE TABLE public.kitchen_inventory (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  inventory_id INTEGER NOT NULL
    REFERENCES public.inventory_items(id) ON DELETE CASCADE,
  quantity NUMERIC(12,2) NOT NULL DEFAULT 0
    CHECK (quantity >= 0),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (restaurant_id, inventory_id)
);

CREATE INDEX kitchen_inventory_restaurant_idx
  ON public.kitchen_inventory(restaurant_id);

CREATE TABLE public.kitchen_inventory_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kitchen_inventory_id INTEGER NOT NULL
    REFERENCES public.kitchen_inventory(id) ON DELETE CASCADE,
  type VARCHAR(20) NOT NULL,
  quantity NUMERIC(12,2) NOT NULL CHECK (quantity > 0),
  note TEXT,
  order_id INTEGER,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX kitchen_inventory_transactions_item_idx
  ON public.kitchen_inventory_transactions(kitchen_inventory_id, created_at DESC);

CREATE TABLE public.kitchen_inventory_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  inventory_id INTEGER NOT NULL
    REFERENCES public.inventory_items(id) ON DELETE RESTRICT,
  requested_quantity NUMERIC(12,2) NOT NULL CHECK (requested_quantity > 0),
  note TEXT,
  requested_by INTEGER
    REFERENCES public.users(id) ON DELETE SET NULL,
  approved_by INTEGER
    REFERENCES public.users(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','approved','rejected')),
  rejection_reason TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX kitchen_inventory_requests_restaurant_idx
  ON public.kitchen_inventory_requests(restaurant_id, status, created_at DESC);

-- ============================================================
-- ORDERS
-- ============================================================
CREATE TABLE public.orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  table_no INTEGER NOT NULL DEFAULT 0,
  local_number INTEGER,

  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,

  customer_name VARCHAR(100),

  status VARCHAR(30) NOT NULL DEFAULT 'pending'
    CHECK (status IN (
      'pending','placed','accepted','preparing','confirmed','ready',
      'served','payment_pending','ready_to_dispatch','ready_to_deliver',
      'out_for_delivery','delivered','paid','completed','cancelled'
    )),

  prep_minutes INTEGER CHECK (prep_minutes IS NULL OR prep_minutes > 0),

  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  confirmed_at TIMESTAMP WITHOUT TIME ZONE,
  ready_at TIMESTAMP WITHOUT TIME ZONE,
  served_at TIMESTAMP WITHOUT TIME ZONE,
  delivered_at TIMESTAMP WITHOUT TIME ZONE,
  completed_at TIMESTAMP WITHOUT TIME ZONE,

  inventory_deducted_at TIMESTAMP WITHOUT TIME ZONE,

  order_source VARCHAR(20) NOT NULL DEFAULT 'MENU'
    CHECK (order_source IN ('MENU','WAITER','COUNTER','PHONE')),

  order_type VARCHAR(20) NOT NULL DEFAULT 'dine_in'
    CHECK (order_type IN ('dine_in','delivery','walk_in')),

  payment_timing VARCHAR(20) NOT NULL DEFAULT 'PAY_LATER'
    CHECK (payment_timing IN ('PAY_LATER','PAID_AT_ORDER','COD')),

  delivery_phone VARCHAR(30),
  delivery_address TEXT,

  payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid'
    CHECK (payment_status IN ('unpaid','paid')),

  payment_method VARCHAR(30),
  paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0
    CHECK (paid_amount >= 0),
  paid_at TIMESTAMP WITHOUT TIME ZONE,
  paid_by_user_id INTEGER
    REFERENCES public.users(id) ON DELETE SET NULL,
  change_amount NUMERIC(12,2) NOT NULL DEFAULT 0
    CHECK (change_amount >= 0),

  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_type VARCHAR(20) NOT NULL DEFAULT 'none',
  discount_value NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  gst_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
  gst_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,

  delivery_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
  dine_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
  card_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
  bank_charge NUMERIC(12,2) NOT NULL DEFAULT 0,

  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,

  created_by_user_id INTEGER
    REFERENCES public.users(id) ON DELETE SET NULL,
  delivery_rider_id INTEGER
    REFERENCES public.users(id) ON DELETE SET NULL
);

CREATE INDEX orders_restaurant_created_idx
  ON public.orders(restaurant_id, created_at DESC);
CREATE INDEX orders_restaurant_status_idx
  ON public.orders(restaurant_id, status);
CREATE INDEX orders_restaurant_payment_idx
  ON public.orders(restaurant_id, payment_status);
CREATE INDEX orders_rider_idx
  ON public.orders(restaurant_id, delivery_rider_id);
CREATE INDEX orders_inventory_deducted_idx
  ON public.orders(restaurant_id, inventory_deducted_at);
CREATE UNIQUE INDEX orders_restaurant_local_number_uq
  ON public.orders(restaurant_id, local_number)
  WHERE local_number IS NOT NULL;

-- ============================================================
-- ORDER LOCAL NUMBER COUNTER
-- ============================================================
CREATE TABLE public.restaurant_order_counters (
  restaurant_id INTEGER PRIMARY KEY
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  next_number INTEGER NOT NULL CHECK (next_number > 0)
);

-- ============================================================
-- ORDER ITEMS
-- ============================================================
CREATE TABLE public.order_deals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL
    REFERENCES public.orders(id) ON DELETE CASCADE,
  deal_id INTEGER NOT NULL
    REFERENCES public.deals(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
  line_total NUMERIC(12,2) NOT NULL CHECK (line_total >= 0)
);

CREATE INDEX order_deals_order_idx ON public.order_deals(order_id);

CREATE TABLE public.order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL
    REFERENCES public.orders(id) ON DELETE CASCADE,
  menu_item_id INTEGER NOT NULL
    REFERENCES public.menu_items(id) ON DELETE RESTRICT,
  variant_id INTEGER
    REFERENCES public.menu_item_variants(id) ON DELETE SET NULL,
  order_deal_id INTEGER
    REFERENCES public.order_deals(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  new_quantity INTEGER NOT NULL DEFAULT 1 CHECK (new_quantity >= 0),
  unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
  line_total NUMERIC(12,2) NOT NULL CHECK (line_total >= 0)
);

CREATE INDEX order_items_order_idx ON public.order_items(order_id);
CREATE INDEX order_items_menu_idx ON public.order_items(menu_item_id);
CREATE INDEX order_items_deal_idx ON public.order_items(order_deal_id);

-- ============================================================
-- INVENTORY RESERVATIONS
-- ============================================================
CREATE TABLE public.inventory_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL
    REFERENCES public.orders(id) ON DELETE CASCADE,
  inventory_id INTEGER NOT NULL
    REFERENCES public.inventory_items(id) ON DELETE RESTRICT,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  quantity NUMERIC(12,3) NOT NULL CHECK (quantity > 0),
  status VARCHAR(20) NOT NULL DEFAULT 'reserved'
    CHECK (status IN ('reserved','consumed','released')),
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  released_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX inventory_reservations_order_idx
  ON public.inventory_reservations(order_id, restaurant_id, status);
CREATE INDEX inventory_reservations_inventory_idx
  ON public.inventory_reservations(inventory_id, restaurant_id, status);

-- ============================================================
-- SUPPLIER PURCHASES / PAYMENTS
-- ============================================================
CREATE TABLE public.supplier_purchases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  supplier_id INTEGER NOT NULL
    REFERENCES public.suppliers(id) ON DELETE RESTRICT,
  purchase_date DATE NOT NULL DEFAULT CURRENT_DATE,
  invoice_no VARCHAR(100),
  total_amount NUMERIC(12,2) NOT NULL CHECK (total_amount > 0),
  paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0
    CHECK (paid_amount >= 0 AND paid_amount <= total_amount),
  note TEXT,
  created_by_user_id INTEGER
    REFERENCES public.users(id) ON DELETE SET NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX supplier_purchases_restaurant_idx
  ON public.supplier_purchases(restaurant_id, purchase_date DESC);
CREATE INDEX supplier_purchases_supplier_idx
  ON public.supplier_purchases(supplier_id, purchase_date DESC);

CREATE TABLE public.supplier_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  supplier_id INTEGER NOT NULL
    REFERENCES public.suppliers(id) ON DELETE RESTRICT,
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  payment_method VARCHAR(50) NOT NULL DEFAULT 'Cash',
  reference_no VARCHAR(150),
  note TEXT,
  created_by_user_id INTEGER
    REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX supplier_payments_restaurant_idx
  ON public.supplier_payments(restaurant_id, payment_date DESC);
CREATE INDEX supplier_payments_supplier_idx
  ON public.supplier_payments(supplier_id, payment_date DESC);

-- ============================================================
-- SHIFTS
-- ============================================================
CREATE TABLE public.shifts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL
    REFERENCES public.users(id) ON DELETE CASCADE,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','closed')),
  started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX shifts_restaurant_idx
  ON public.shifts(restaurant_id, started_at DESC);
CREATE INDEX shifts_user_idx
  ON public.shifts(user_id, restaurant_id, status);

CREATE UNIQUE INDEX shifts_one_active_per_user
  ON public.shifts(user_id, restaurant_id)
  WHERE status = 'active';

-- ============================================================
-- QR PAYMENTS
-- ============================================================
CREATE TABLE public.qr_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  order_id INTEGER NOT NULL
    REFERENCES public.orders(id) ON DELETE RESTRICT,
  qr_id VARCHAR(150) NOT NULL UNIQUE,
  provider VARCHAR(50) NOT NULL DEFAULT 'manual',
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','paid','expired','cancelled','failed')),
  qr_string TEXT,
  qr_image_url TEXT,
  provider_ref VARCHAR(255),
  paid_at TIMESTAMP WITHOUT TIME ZONE,
  paid_amount NUMERIC(12,2),
  payment_method VARCHAR(50),
  expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  raw_response JSONB,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX qr_payments_restaurant_idx
  ON public.qr_payments(restaurant_id, created_at DESC);
CREATE INDEX qr_payments_order_idx
  ON public.qr_payments(restaurant_id, order_id);
CREATE INDEX qr_payments_pending_idx
  ON public.qr_payments(order_id, status, expires_at);

-- ============================================================
-- IMMUTABLE PAYMENT LEDGER
-- ============================================================
CREATE TABLE public.payment_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  order_id INTEGER NOT NULL
    REFERENCES public.orders(id) ON DELETE RESTRICT,
  qr_payment_id BIGINT
    REFERENCES public.qr_payments(id) ON DELETE SET NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  payment_method VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'completed'
    CHECK (status IN ('completed','refunded','failed')),
  provider_ref VARCHAR(255),
  reference VARCHAR(255),
  actor_user_id INTEGER
    REFERENCES public.users(id) ON DELETE SET NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX payment_transactions_restaurant_idx
  ON public.payment_transactions(restaurant_id, created_at DESC);
CREATE INDEX payment_transactions_order_idx
  ON public.payment_transactions(restaurant_id, order_id, created_at DESC);
CREATE INDEX payment_transactions_qr_idx
  ON public.payment_transactions(qr_payment_id)
  WHERE qr_payment_id IS NOT NULL;

-- Payment ledger is append-only.
CREATE OR REPLACE FUNCTION public.prevent_payment_transaction_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'payment_transactions is append-only; use a new transaction row';
END;
$$;

CREATE TRIGGER payment_transactions_no_update
BEFORE UPDATE ON public.payment_transactions
FOR EACH ROW EXECUTE FUNCTION public.prevent_payment_transaction_mutation();

CREATE TRIGGER payment_transactions_no_delete
BEFORE DELETE ON public.payment_transactions
FOR EACH ROW EXECUTE FUNCTION public.prevent_payment_transaction_mutation();

-- ============================================================
-- PUBLIC ORDER IDEMPOTENCY
-- ============================================================
CREATE TABLE public.public_order_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  idempotency_key VARCHAR(128) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  order_id INTEGER
    REFERENCES public.orders(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'processing'
    CHECK (status IN ('processing','completed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (restaurant_id, idempotency_key)
);

CREATE INDEX public_order_requests_order_idx
  ON public.public_order_requests(restaurant_id, order_id);
CREATE INDEX public_order_requests_updated_idx
  ON public.public_order_requests(updated_at);

-- ============================================================
-- FBR INVOICES
-- ============================================================
CREATE TABLE public.fbr_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL
    REFERENCES public.orders(id) ON DELETE RESTRICT,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','submitted','failed')),
  fbr_invoice_number VARCHAR(255),
  fbr_qr_code TEXT,
  request_payload JSONB,
  response_payload JSONB,
  retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
  last_error TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  submitted_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX fbr_invoices_restaurant_idx
  ON public.fbr_invoices(restaurant_id, status, created_at DESC);
CREATE INDEX fbr_invoices_order_idx
  ON public.fbr_invoices(restaurant_id, order_id);

-- ============================================================
-- WHOLESALE
-- ============================================================
CREATE TABLE public.wholesale_products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  sku VARCHAR(100),
  unit VARCHAR(30) NOT NULL DEFAULT 'pcs',
  purchase_price NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (purchase_price >= 0),
  sale_price NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (sale_price >= 0),
  stock NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (stock >= 0),
  min_stock NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (min_stock >= 0),
  category VARCHAR(100),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX wholesale_products_restaurant_idx
  ON public.wholesale_products(restaurant_id, active);

CREATE TABLE public.wholesale_invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL
    REFERENCES public.restaurants(id) ON DELETE CASCADE,
  local_number INTEGER NOT NULL,
  customer_name VARCHAR(150) DEFAULT 'Walk-in',
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  paid NUMERIC(12,2) NOT NULL DEFAULT 0,
  payment_type VARCHAR(30) NOT NULL DEFAULT 'cash',
  status VARCHAR(30) NOT NULL DEFAULT 'completed',
  created_by INTEGER
    REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (restaurant_id, local_number)
);

CREATE INDEX wholesale_invoices_restaurant_idx
  ON public.wholesale_invoices(restaurant_id, created_at DESC);

CREATE TABLE public.wholesale_invoice_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL
    REFERENCES public.wholesale_invoices(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL
    REFERENCES public.wholesale_products(id) ON DELETE RESTRICT,
  name VARCHAR(150) NOT NULL,
  qty NUMERIC(12,2) NOT NULL CHECK (qty > 0),
  unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
  line_total NUMERIC(12,2) NOT NULL CHECK (line_total >= 0)
);

CREATE INDEX wholesale_invoice_items_invoice_idx
  ON public.wholesale_invoice_items(invoice_id);

-- ============================================================
-- FRESH DATABASE SANITY INDEXES / CONSTRAINT SUPPORT
-- ============================================================
CREATE INDEX orders_created_by_idx
  ON public.orders(created_by_user_id, restaurant_id);
CREATE INDEX orders_paid_by_idx
  ON public.orders(paid_by_user_id, restaurant_id);

COMMIT;
