-- Sizlio POS migration 016: complete production schema reconciliation
-- Purpose: bring existing installations up to the same table coverage as
-- server/restaurant_pos_schema.sql. Safe to re-run.
BEGIN;

-- Core columns that may be absent on older installations.
ALTER TABLE public.restaurants
  ADD COLUMN IF NOT EXISTS pos_settings JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS raast_qr_string TEXT,
  ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7),
  ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7),
  ADD COLUMN IF NOT EXISTS gps_radius_meters NUMERIC(10,2) NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS fbr_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS fbr_pos_registration_no VARCHAR(100),
  ADD COLUMN IF NOT EXISTS fbr_api_token TEXT,
  ADD COLUMN IF NOT EXISTS fbr_seller_ntn_cnic VARCHAR(100),
  ADD COLUMN IF NOT EXISTS fbr_seller_business_name VARCHAR(200),
  ADD COLUMN IF NOT EXISTS fbr_seller_province VARCHAR(100),
  ADD COLUMN IF NOT EXISTS fbr_seller_address TEXT,
  ADD COLUMN IF NOT EXISTS fbr_environment VARCHAR(20) NOT NULL DEFAULT 'sandbox';

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS customer_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS prep_minutes INTEGER,
  ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS ready_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS served_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS order_source VARCHAR(20) NOT NULL DEFAULT 'MENU',
  ADD COLUMN IF NOT EXISTS order_type VARCHAR(20) NOT NULL DEFAULT 'dine_in',
  ADD COLUMN IF NOT EXISTS payment_timing VARCHAR(20) NOT NULL DEFAULT 'PAY_LATER',
  ADD COLUMN IF NOT EXISTS delivery_phone VARCHAR(30),
  ADD COLUMN IF NOT EXISTS delivery_address TEXT,
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
  ADD COLUMN IF NOT EXISTS payment_method VARCHAR(30),
  ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS paid_by_user_id INTEGER,
  ADD COLUMN IF NOT EXISTS created_by_user_id INTEGER,
  ADD COLUMN IF NOT EXISTS delivery_rider_id INTEGER,
  ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_type VARCHAR(20) NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS discount_value NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gst_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gst_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tax_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dine_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS card_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bank_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS change_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS inventory_deducted_at TIMESTAMP;

ALTER TABLE public.order_items
  ADD COLUMN IF NOT EXISTS variant_id INTEGER,
  ADD COLUMN IF NOT EXISTS order_deal_id INTEGER,
  ADD COLUMN IF NOT EXISTS new_quantity INTEGER NOT NULL DEFAULT 1;

ALTER TABLE public.menu_item_ingredients
  ADD COLUMN IF NOT EXISTS variant_id INTEGER;

-- Missing application tables.
CREATE TABLE IF NOT EXISTS public.menu_item_variants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_item_id INTEGER NOT NULL REFERENCES public.menu_items(id) ON DELETE CASCADE,
  label VARCHAR(100) NOT NULL,
  price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (menu_item_id, label)
);

CREATE TABLE IF NOT EXISTS public.deals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  price NUMERIC(12,2) NOT NULL DEFAULT 0,
  type VARCHAR(50) NOT NULL DEFAULT 'deal',
  category VARCHAR(100),
  image TEXT,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.deal_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id INTEGER NOT NULL REFERENCES public.deals(id) ON DELETE CASCADE,
  menu_item_id INTEGER NOT NULL REFERENCES public.menu_items(id) ON DELETE RESTRICT,
  variant_id INTEGER REFERENCES public.menu_item_variants(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS public.order_deals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  deal_id INTEGER NOT NULL REFERENCES public.deals(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  line_total NUMERIC(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.inventory_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  inventory_id INTEGER NOT NULL REFERENCES public.inventory_items(id) ON DELETE RESTRICT,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  quantity NUMERIC(12,3) NOT NULL CHECK (quantity > 0),
  status VARCHAR(20) NOT NULL DEFAULT 'reserved',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  released_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.kitchen_inventory (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  inventory_id INTEGER NOT NULL REFERENCES public.inventory_items(id) ON DELETE CASCADE,
  quantity NUMERIC(12,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (restaurant_id, inventory_id)
);

CREATE TABLE IF NOT EXISTS public.kitchen_inventory_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kitchen_inventory_id INTEGER NOT NULL REFERENCES public.kitchen_inventory(id) ON DELETE CASCADE,
  type VARCHAR(20) NOT NULL,
  quantity NUMERIC(12,2) NOT NULL,
  note TEXT,
  order_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.kitchen_inventory_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  inventory_id INTEGER NOT NULL REFERENCES public.inventory_items(id) ON DELETE RESTRICT,
  requested_quantity NUMERIC(12,2) NOT NULL,
  note TEXT,
  requested_by INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  approved_by INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  rejection_reason TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.supplier_purchases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  supplier_id INTEGER NOT NULL REFERENCES public.suppliers(id) ON DELETE RESTRICT,
  purchase_date DATE NOT NULL DEFAULT CURRENT_DATE,
  invoice_no VARCHAR(100),
  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  note TEXT,
  created_by_user_id INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.supplier_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  supplier_id INTEGER NOT NULL REFERENCES public.suppliers(id) ON DELETE RESTRICT,
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  amount NUMERIC(12,2) NOT NULL,
  payment_method VARCHAR(50) NOT NULL DEFAULT 'Cash',
  reference_no VARCHAR(150),
  note TEXT,
  created_by_user_id INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.shifts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  started_at TIMESTAMP NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.qr_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  order_id INTEGER NOT NULL REFERENCES public.orders(id) ON DELETE RESTRICT,
  qr_id VARCHAR(150) NOT NULL UNIQUE,
  provider VARCHAR(50) NOT NULL DEFAULT 'manual',
  amount NUMERIC(12,2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  qr_string TEXT,
  qr_image_url TEXT,
  provider_ref VARCHAR(255),
  paid_at TIMESTAMP,
  paid_amount NUMERIC(12,2),
  payment_method VARCHAR(50),
  expires_at TIMESTAMP NOT NULL,
  raw_response JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.payment_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  order_id INTEGER NOT NULL REFERENCES public.orders(id) ON DELETE RESTRICT,
  qr_payment_id BIGINT,
  amount NUMERIC(12,2) NOT NULL,
  payment_method VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'completed',
  provider_ref VARCHAR(255),
  reference VARCHAR(255),
  actor_user_id INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.public_order_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  idempotency_key VARCHAR(128) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  order_id INTEGER REFERENCES public.orders(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'processing',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (restaurant_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.fbr_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES public.orders(id) ON DELETE RESTRICT,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  fbr_invoice_number VARCHAR(255),
  fbr_qr_code TEXT,
  request_payload JSONB,
  response_payload JSONB,
  retry_count INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  submitted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.wholesale_products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  sku VARCHAR(100),
  unit VARCHAR(30) NOT NULL DEFAULT 'pcs',
  purchase_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  sale_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  stock NUMERIC(12,2) NOT NULL DEFAULT 0,
  min_stock NUMERIC(12,2) NOT NULL DEFAULT 0,
  category VARCHAR(100),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.wholesale_invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  local_number INTEGER NOT NULL,
  customer_name VARCHAR(150) DEFAULT 'Walk-in',
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  paid NUMERIC(12,2) NOT NULL DEFAULT 0,
  payment_type VARCHAR(30) NOT NULL DEFAULT 'cash',
  status VARCHAR(30) NOT NULL DEFAULT 'completed',
  created_by INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (restaurant_id, local_number)
);

CREATE TABLE IF NOT EXISTS public.wholesale_invoice_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL REFERENCES public.wholesale_invoices(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES public.wholesale_products(id) ON DELETE RESTRICT,
  name VARCHAR(150) NOT NULL,
  qty NUMERIC(12,2) NOT NULL,
  unit_price NUMERIC(12,2) NOT NULL,
  line_total NUMERIC(12,2) NOT NULL
);

-- Counters/indexes used by concurrent order and tenant-scoped queries.
CREATE TABLE IF NOT EXISTS public.restaurant_order_counters (
  restaurant_id INTEGER PRIMARY KEY REFERENCES public.restaurants(id) ON DELETE CASCADE,
  next_number INTEGER NOT NULL CHECK (next_number > 0)
);

CREATE INDEX IF NOT EXISTS orders_restaurant_status_idx
  ON public.orders(restaurant_id, status);
CREATE INDEX IF NOT EXISTS orders_restaurant_payment_idx
  ON public.orders(restaurant_id, payment_status);
CREATE INDEX IF NOT EXISTS orders_rider_idx
  ON public.orders(restaurant_id, delivery_rider_id);
CREATE INDEX IF NOT EXISTS orders_inventory_deducted_idx
  ON public.orders(restaurant_id, inventory_deducted_at);

DO $
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'order_items_order_deal_id_fkey'
  ) THEN
    ALTER TABLE public.order_items
      ADD CONSTRAINT order_items_order_deal_id_fkey
      FOREIGN KEY (order_deal_id) REFERENCES public.order_deals(id)
      ON DELETE CASCADE NOT VALID;
  END IF;
END $;

DO $
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'menu_item_ingredients_variant_id_fkey'
  ) THEN
    ALTER TABLE public.menu_item_ingredients
      ADD CONSTRAINT menu_item_ingredients_variant_id_fkey
      FOREIGN KEY (variant_id) REFERENCES public.menu_item_variants(id)
      ON DELETE CASCADE NOT VALID;
  END IF;
END $;

-- Existing payment ledger installations may predate the QR FK.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'payment_transactions_qr_payment_id_fkey'
  ) THEN
    ALTER TABLE public.payment_transactions
      ADD CONSTRAINT payment_transactions_qr_payment_id_fkey
      FOREIGN KEY (qr_payment_id) REFERENCES public.qr_payments(id)
      ON DELETE SET NULL;
  END IF;
END $$;

COMMIT;
